[workspace]

[package]
name = "finance_tracker"
version = "0.1.0"
edition = "2021"
publish = false
default-run = "finance_tracker-cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
loco-rs = { version = "0.12.0" }

[dependencies]

loco-rs = { workspace = true }
migration = { path = "migration" }

simplefin-bridge = { path = "./simplefin-bridge" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-trait = "0.1.74"
tokio = { version = "1.33.0", default-features = false }
tracing = "0.1.40"
chrono = "0.4"
validator = { version = "0.18" }
sea-orm = { version = "1.1.0", features = [
  "sqlx-sqlite",
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
  "debug-print"
] }

axum = "0.7.5"
include_dir = "0.7"
uuid = { version = "1.6.0", features = ["v4"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }

# view engine i18n
fluent-templates = { version = "0.8.0", features = ["tera"] }
unic-langid = "0.9.4"
dotenv = "0.15.0"
thiserror = "2.0.11"
url = "2.5.4"
prettytable-rs = "0.10.0"
rust_decimal = "1.36.0"
llm = { version = "1.0.4", features = ["openai", "anthropic", "ollama", "deepseek", "xai", "phind", "google", "groq", "api"] }
reqwest = "0.12.12"
chrono-tz = "0.10.1"
# /view engine

[[bin]]
name = "finance_tracker-cli"
path = "src/bin/main.rs"
required-features = []



[[bin]]
name = "tool"
path = "src/bin/tool.rs"
required-features = []

[dev-dependencies]
serial_test = "3.1.1"
rstest = "0.21.0"
loco-rs = { workspace = true, features = ["testing"] }
insta = { version = "1.34.0", features = ["redactions", "yaml", "filters"] }

