package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/rs/zerolog/log"

	"finance_tracker/internal/billing"
	"finance_tracker/internal/config"
	llmclient "finance_tracker/internal/llm"
	"finance_tracker/internal/models"
	"finance_tracker/internal/notify"
	"finance_tracker/internal/scheduler"
	"finance_tracker/internal/store"
)

// AnalysisRunHandler handles on-demand and scheduled analysis runs.
type AnalysisRunHandler struct {
	cfg           *config.Config
	txnStore      *store.TransactionStore
	acctStore     *store.AccountStore
	analysisStore *store.AnalysisStore
	settingsStore *store.SettingsStore
	catStore      *store.CategoryStore
	scheduler     *scheduler.Scheduler
	events        *EventHub
}

func NewAnalysisRunHandler(
	cfg *config.Config,
	txns *store.TransactionStore,
	accts *store.AccountStore,
	analyses *store.AnalysisStore,
	settings *store.SettingsStore,
	cats *store.CategoryStore,
	sched *scheduler.Scheduler,
	events *EventHub,
) *AnalysisRunHandler {
	return &AnalysisRunHandler{
		cfg:           cfg,
		txnStore:      txns,
		acctStore:     accts,
		analysisStore: analyses,
		settingsStore: settings,
		catStore:      cats,
		scheduler:     sched,
		events:        events,
	}
}

func (h *AnalysisRunHandler) TriggerAnalysis(w http.ResponseWriter, r *http.Request) {
	if !h.scheduler.TryAcquire("analysis") {
		WriteError(w, http.StatusConflict, "OP_IN_PROGRESS",
			"Another operation is running: "+h.scheduler.CurrentJob())
		return
	}

	go func() {
		defer h.scheduler.Release()
		h.runAnalysis(context.Background())
	}()

	WriteJSON(w, http.StatusAccepted, Response{Data: map[string]string{"status": "started"}})
}

func (h *AnalysisRunHandler) runAnalysis(ctx context.Context) {
	h.events.Broadcast("analysis_started", `{"status":"running"}`)

	// Get billing day from settings.
	billingDay := 15
	if val, err := h.settingsStore.Get(ctx, "billing_day"); err == nil && val != "" {
		if d := parseInt(val); d >= 1 && d <= 28 {
			billingDay = d
		}
	}

	// Determine analysis type: use multi-period (5 cycles) by default.
	dateRangeType := models.DateRangeTypeCurrentAndLastMonth
	startDate, endDate, err := billing.CalculateDateRange(dateRangeType, nil, nil, billingDay)
	if err != nil {
		log.Error().Err(err).Msg("Failed to calculate date range for analysis")
		h.events.Broadcast("analysis_error", fmt.Sprintf(`{"error":"%s"}`, err.Error()))
		return
	}

	// Fetch transactions for the period.
	txns, err := h.txnStore.GetForPeriod(ctx, startDate.Unix(), endDate.Unix())
	if err != nil {
		log.Error().Err(err).Msg("Failed to fetch transactions for analysis")
		h.events.Broadcast("analysis_error", fmt.Sprintf(`{"error":"%s"}`, err.Error()))
		return
	}

	if len(txns) == 0 {
		log.Warn().Msg("No transactions found for analysis period")
		h.events.Broadcast("analysis_error", `{"error":"No transactions found for the analysis period"}`)
		return
	}

	// Get accounts.
	accounts, err := h.acctStore.List(ctx)
	if err != nil {
		log.Error().Err(err).Msg("Failed to fetch accounts for analysis")
		h.events.Broadcast("analysis_error", fmt.Sprintf(`{"error":"%s"}`, err.Error()))
		return
	}

	// Build prompt.
	prompt := llmclient.GeneratePrompt(txns, accounts, startDate, endDate, billingDay, true)

	// Get LLM settings (prefer DB settings, fall back to env config).
	openRouterURL := h.cfg.OpenRouterURL
	if v, _ := h.settingsStore.Get(ctx, "openrouter_url"); v != "" {
		openRouterURL = v
	}
	openRouterKey := h.cfg.OpenRouterAPIKey
	if v, _ := h.settingsStore.Get(ctx, "openrouter_api_key"); v != "" {
		openRouterKey = v
	}
	openRouterModel := h.cfg.OpenRouterModel
	if v, _ := h.settingsStore.Get(ctx, "openrouter_model"); v != "" {
		openRouterModel = v
	}

	if openRouterURL == "" || openRouterKey == "" || openRouterModel == "" {
		log.Error().Msg("OpenRouter not configured")
		h.events.Broadcast("analysis_error", `{"error":"OpenRouter not configured. Set API key and model in Settings."}`)
		return
	}

	llm := llmclient.NewClient(openRouterURL, openRouterKey, openRouterModel)

	// Call LLM with retry.
	response, err := llmclient.RetryWithBackoff(func() (string, error) {
		content, model, err := llm.Analyze(llmclient.SystemPrompt, prompt, true)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("%s\n\n---\n*Generated by %s*", content, model), nil
	}, 3, 2, "LLM analysis")

	status := "success"
	if err != nil {
		log.Error().Err(err).Msg("LLM analysis failed")
		response = fmt.Sprintf("Analysis failed: %s", err.Error())
		status = "error"
	}

	// Store result.
	_, storeErr := h.analysisStore.Create(ctx, models.Analysis{
		PeriodStart:   startDate.Unix(),
		PeriodEnd:     endDate.Unix(),
		BillingDay:    billingDay,
		DateRangeType: string(dateRangeType),
		ResponseText:  response,
		IsMultiPeriod: true,
		Status:        status,
	})
	if storeErr != nil {
		log.Error().Err(storeErr).Msg("Failed to store analysis result")
	}

	if status == "success" {
		h.events.Broadcast("analysis_complete", `{"status":"success"}`)
		log.Info().Msg("Analysis complete")

		// Send notifications.
		h.sendNotifications(response, txns)
	} else {
		h.events.Broadcast("analysis_error", fmt.Sprintf(`{"error":"%s"}`, err.Error()))
	}
}

func (h *AnalysisRunHandler) sendNotifications(message string, txns []models.DBTransaction) {
	dispatcher := notify.NewDispatcher(notify.Config{
		NtfyServer:        h.cfg.NtfyServer,
		NtfyTopic:         h.cfg.NtfyTopic,
		NtfyWarningSuffix: h.cfg.NtfyWarningSuffix,
		MailerURL:         h.cfg.MailerURL,
		MailerFrom:        h.cfg.MailerFrom,
		MailerTo:          h.cfg.MailerTo,
	})

	channels, err := dispatcher.Send(message, txns, "info")
	if err != nil {
		log.Error().Err(err).Msg("Failed to send analysis notifications")
	} else if len(channels) > 0 {
		log.Info().Strs("channels", channels).Msg("Notifications sent")
	}
}

// RunAnalysis is called by the scheduler for periodic analysis.
func (h *AnalysisRunHandler) RunAnalysis() {
	if !h.scheduler.TryAcquire("scheduled_analysis") {
		log.Warn().Msg("Skipping scheduled analysis: another operation is running")
		return
	}
	defer h.scheduler.Release()
	h.runAnalysis(context.Background())
}

func parseInt(s string) int {
	var n int
	for _, c := range s {
		if c >= '0' && c <= '9' {
			n = n*10 + int(c-'0')
		}
	}
	return n
}

// Suppress unused import.
var _ = time.Now
