name: Release
on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
    branches:
      - master
      - main

env:
  RUST_TOOLCHAIN: stable
  TOOLCHAIN_PROFILE: minimal

jobs:
  build:
    name: Build Binary (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]

    permissions:
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: Install cross-compilation tools
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          targets: ${{ matrix.target }}
      
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
      
      - name: Configure for size optimization
        run: |
          # Create .cargo/config.toml to optimize for small binary size
          mkdir -p .cargo
          cat > .cargo/config.toml << EOF
          [profile.release]
          opt-level = "z"  # Optimize for size
          lto = true       # Enable link-time optimization
          codegen-units = 1 # Use a single codegen unit for better optimization
          panic = "abort"   # Removes panic unwinding code
          strip = true      # Strip symbols from binary
          EOF
      
      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
          CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
          CXX_aarch64_unknown_linux_gnu: aarch64-linux-gnu-g++
          RUSTFLAGS: "-C strip=symbols"
      
      - name: Strip binary
        run: |
          if [ "${{ matrix.target }}" == "x86_64-unknown-linux-gnu" ]; then
            strip "target/${{ matrix.target }}/release/finance-tracker"
          else
            aarch64-linux-gnu-strip "target/${{ matrix.target }}/release/finance-tracker"
          fi
      
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: finance-tracker-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/finance-tracker
          retention-days: 1

  tag-release:
    name: Create New Version Tag
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    permissions:
      contents: write  # Needed for creating tags

    outputs:
      new_tag: ${{ steps.get_latest_tag.outputs.version }}  # Make tag available to next job

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for tags
      
      - name: Get latest tag
        id: get_latest_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag -l 'v*' --sort=-v:refname | head -n 1)
          if [ -z "$latest_tag" ]; then
            echo "version=v0.1.0" >> "$GITHUB_OUTPUT"
          else
            # Split version into parts
            major=$(echo "$latest_tag" | cut -d. -f1)
            minor=$(echo "$latest_tag" | cut -d. -f2)
            patch=$(echo "$latest_tag" | cut -d. -f3)
            
            # Increment patch version
            new_patch=$((patch + 1))
            new_version="${major}.${minor}.${new_patch}"
            
            echo "version=$new_version" >> "$GITHUB_OUTPUT"
          fi

      - name: Create and push tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          new_tag="${{ steps.get_latest_tag.outputs.version }}"
          git tag "$new_tag"
          git push origin "$new_tag"
          echo "Created and pushed new tag: $new_tag"

  create-release:
    name: Create Release from Tag
    needs: [build, tag-release]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    permissions:
      contents: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: Download x86_64 binary
        uses: actions/download-artifact@v4
        with:
          name: finance-tracker-x86_64-unknown-linux-gnu
          path: release-bins/x86_64
      
      - name: Download aarch64 binary
        uses: actions/download-artifact@v4
        with:
          name: finance-tracker-aarch64-unknown-linux-gnu
          path: release-bins/aarch64
      
      - name: Prepare binaries
        run: |
          mkdir -p release-bins/final
          # Copy binaries to final location with architecture suffix
          cp release-bins/x86_64/finance-tracker release-bins/final/finance-tracker-x86_64
          cp release-bins/aarch64/finance-tracker release-bins/final/finance-tracker-aarch64
          chmod +x release-bins/final/finance-tracker-*
          # Check final binary sizes
          ls -la release-bins/final/

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          new_tag="${{ needs.tag-release.outputs.new_tag }}"
          
          # Create a new release
          gh release create "$new_tag" \
            --title "$new_tag" \
            --generate-notes \
            "release-bins/final/finance-tracker-x86_64" \
            "release-bins/final/finance-tracker-aarch64" 

  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: [tag-release]
    permissions:
      contents: read
      packages: write

    steps:    
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache dockerfile
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/dockerfile') }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ needs.tag-release.outputs.new_tag }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache