name: Go Formatting

# Run on push to any branch and on pull requests
on:
  push:
    branches: ['**']
  pull_request:
  workflow_dispatch:  # Allow manual triggering

jobs:
  gofmt:
    name: Check Go Style
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Run gofmt
        run: |
          if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
            echo "The following files are not formatted:"
            gofmt -l .
            exit 1
          fi
